### ISSUE TITLE
ability to download the image generated

### ISSUE THREAD

**Issue by goutham2688** [arichika/previewseqdiag-vscode#21]
how can i download the images generated with this extension? 

version:0.2.3
VSCode version: 1.42.1

**Comment by arichika** [comment]
The function is not yet available. I think I want it too.
Now, use the conversion function on the official website of each language to convert the image into the required format.

**Comment by moshe-datasya** [comment]
I would really love to see that! Adding buttons to save as HPG, PNG and SVG hovering over the preview

**Comment by arichika** [comment]
Please wait a little.
I'll try to add it.

**Comment by arichika** [comment]
Released 🎉  0.4.0

https://github.com/arichika/previewseqdiag-vscode/releases/tag/0.4.0
https://marketplace.visualstudio.com/items?itemName=arichika.previewseqdiag-vscode

### PNG: 
* Save Image as PNG.   
* Since mermaid has a transparent background by default, PNG keep it that way.

### PNG*:  
* Save Image as PNG, As you see it.   
* The SVG data generated by mermaid's library does not include a background color. The 'PNG*' button to generate a PNG image with a specified background color as you see it.

###JPEG:  
* Save Image as JPG, As you see it.  On Mac, the background is environment-dependent when saving JPEGs; in Dark mode, it is not what it looks like, so I forced it to match the preview.

### SVG
* Save SVG file. 
* Since mermaid has a transparent background by default, SVG keep it that way.
  
### Clipboard
* Copy to Clipboard by PNG. ()
* Since mermaid has a transparent background by default, PNG keep it that way.

<img width="986" alt="image" src="https://user-images.githubusercontent.com/1038874/161366253-7e1482ed-d66d-4c8d-852f-c7fd50663b54.png">

**Comment by moshe-datasya** [comment]
I'm speechless! thank you!

![image](https://user-images.githubusercontent.com/94912788/161430726-e8b94209-0a69-44e9-9020-f1328909e06a.png)
